language: r
sudo: false
cache: packages

env:
  - R_RVERSIONS_CRAN_URL='https://cloud.r-project.org'
  
matrix:
  include:
   - r: release
     before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
     deploy:
       provider: script
       script: Rscript -e 'pkgdown::deploy_site_github()'
       skip_cleanup: true
   - r: devel
   - r: oldrel

after_success:
  - Rscript -e 'covr::codecov()'
 
